apps/news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import news_list, view_news_detail

# from .views import create_news, edit_news, delete_news

urlpatterns = [
    path('', news_list, name='news_list'),
    # path('create/', create_news, name='create_news'),
    path('<int:pk>/', view_news_detail, name='view_news_detail'),
    # path('<int:pk>/edit/', edit_news, name='edit_news'),
    # path('<int:pk>/delete/', delete_news, name='delete_news'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf.urls.static import static
from django.conf import settings


schema_view = get_schema_view(
   openapi.Info(
      title="Deep",
      default_version='v1',
      description="This is Deep API",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="None"),
      license=openapi.License(name="MentorKG License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('account/', include('apps.account.urls')),
    path('teachers/', include('apps.teachers.urls')),
    path('positions/', include('apps.positions.urls')),
    path('news/', include('apps.news.urls')),
    path('additional-materials/', include('apps.additionalMaterials.urls')),
    path('curriculum/', include('apps.curriculum.urls')),
    path('textbooks/', include('apps.textbooks.urls')),
    path('web-materials/', include('apps.webMaterials.urls')),
    path('subjects/', include('apps.subjects.urls')),
]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/news/models.py
from django.db import models

class News(models.Model):
    headline = models.CharField(max_length=255, null=True)
    content = models.TextField(null=True)
    publication_date = models.DateField(null=True)
    image = models.ImageField(upload_to='news_images/', null=True, blank=True)

    class Meta:
        db_table = 'News'

    def __str__(self):
        return f'{self.headline}: {self.publication_date}'

apps/news/forms.py
# news/forms.py
from django import forms
from .models import News

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['headline', 'content', 'publication_date', 'image']

apps/news/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import News
from .forms import NewsForm


def news_list(request):
    news_items = News.objects.all()
    return render(request, 'news/news_list.html', {'news_items': news_items})


# def create_news(request):
#     if request.method == 'POST':
#         form = NewsForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('news_list')
#     else:
#         form = NewsForm()
#
#     return render(request, 'news/create_news.html', {'form': form})


def view_news_detail(request, pk):
    news_item = get_object_or_404(News, pk=pk)
    return render(request, 'news/view_news_detail.html', {'news_item': news_item})


# def edit_news(request, pk):
#     news_item = get_object_or_404(News, pk=pk)
#     if request.method == 'POST':
#         form = NewsForm(request.POST, request.FILES, instance=news_item)
#         if form.is_valid():
#             form.save()
#             return redirect('view_news_detail', pk=pk)
#     else:
#         form = NewsForm(instance=news_item)
#
#     return render(request, 'news/edit_news.html', {'form': form, 'news_item': news_item})
#
#
# def delete_news(request, pk):
#     news_item = get_object_or_404(News, pk=pk)
#     if request.method == 'POST':
#         news_item.delete()
#         return redirect('news_list')
#
#     return render(request, 'news/delete_news.html', {'news_item': news_item})

apps/news/templates/news/create_news.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create News</title>
    <link rel="stylesheet" href="{% static 'news/create-style.css' %}">
</head>
<body>
    <div class="container">
        <h1>Добавить Новость</h1>
        <form method="post" enctype="multipart/form-data" class="custom-form">
            {% csrf_token %}
            <div class="form-group">
                    <label for="id_headline">Заголовок:</label>
                {{ form.headline }}
            </div>
            <div class="form-group">
                <label for="id_content">Содержание:</label>
                {{ form.content }}
            </div>
            <div class="form-group">
                <label for="id_publication_date">Дата публикации:</label>
                {{ form.publication_date }}
            </div>
            <div class="form-group">
                <label for="id_image">Фото:</label>
                {{ form.image }}
            </div>
            <button type="submit">Создать</button>
        </form>
    </div>
</body>
</html>

apps/news/templates/news/delete_news.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete News</title>
    <link rel="stylesheet" href="{% static 'news/styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Вы уверены, что хотите удалить эту новость?</h1>
        <p>{{ news_item.headline }}</p>
        <form method="post" class="custom-form">
            {% csrf_token %}
            <button type="submit">Delete</button>
        </form>
        <a href="{% url 'view_news_detail' news_item.id %}" class="back-button">Cancel</a>
    </div>
</body>
</html>

apps/news/templates/news/edit_news.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit News</title>
    <link rel="stylesheet" href="{% static 'news/edit-style.css' %}">
    <style>
        .clear-checkbox {
            display: none;
        }
    </style>
    <script>
        function clearImage() {
            var imageInput = document.getElementById('id_image');
            if (imageInput) {
                imageInput.value = '';
            }
            var currentImageText = document.getElementById('current-image');
            if (currentImageText) {
                currentImageText.innerHTML = 'На данный момент: Изображение очищено';
            }
            var clearCheckbox = document.getElementById('id_image-clear_id');
            if (clearCheckbox) {
                clearCheckbox.checked = true;
            }
        }
    </script>
</head>
<body>
    <div class="container">
        <h1>Редактирование Новости</h1>
        <form method="post" enctype="multipart/form-data" class="custom-form">
            {% csrf_token %}
            <div>
                {{ form.headline.label_tag }} {{ form.headline }}
            </div>
            <div>
                {{ form.content.label_tag }} {{ form.content }}
            </div>
            <div>
                {{ form.publication_date.label_tag }} {{ form.publication_date }}
            </div>
            <div>
                {{ form.image.label_tag }}
                <div id="current-image">На данный момент:
                    {% if form.instance.image %}
                        <a href="{{ form.instance.image.url }}">{{ form.instance.image.name }}</a>
                    {% else %}
                        Изображение не загружено
                    {% endif %}
                </div>
                <button type="button" onclick="clearImage()">Очистить фото</button>
                <div class="clear-checkbox">
                    {{ form.image.delete_checkbox }}
                </div>
            </div>
            <button type="submit">Сохранить</button>
        </form>
        <a href="{% url 'view_news_detail' news_item.id %}" class="back-button">Отмена</a>
    </div>
</body>
</html>

apps/news/templates/news/news_list.html
{% extends 'home/layout.html' %}

{% load static %}


{% block headcontent %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Новости</title>
    <link rel="stylesheet" href="{% static 'news/news-style.css' %}">
{% endblock %}

{% block bodycontent %}
<body>
{% include 'home/navbar.html' %}
<h1>Новости</h1>
<div class="container">
    <div id="news-cards" class="news-cards"></div>
{#    <a href="{% url 'create_news' %}" class="create-button">Добавить новость</a>#}
</div>

<script>
    // Функция для загрузки новостей из Django шаблонов
    function loadNews() {
        const news_items = [
            {% for news in news_items %}
                {
                    id: "{{ news.id }}",
                    title: "{{ news.headline }}",
                    content: "{{ news.content|truncatechars:100 }}",
                    image: "{% if news.image %}{{ news.image.url }}{% endif %}",
                    publication_date: "{{ news.publication_date }}"
                },
            {% endfor %}
        ];
        return news_items;
    }

    // Функция для отображения новостей в виде карточек
    function displayNewsCards(news) {
        const newsCardsContainer = document.getElementById('news-cards');
        newsCardsContainer.innerHTML = '';
        news.forEach((newsItem) => {
            const card = document.createElement('div');
            card.className = 'card';
            card.innerHTML = `
            ${newsItem.image ? `<img src="${newsItem.image}" alt="${newsItem.title}" class="news-image">` : ''}
            <h2>${newsItem.title}</h2>
            <p>${newsItem.content}...</p>
            <a href="/news/${newsItem.id}/" class="read-more-button">Читать полностью</a>
        `;
            newsCardsContainer.appendChild(card);
        });
    }

    // Функция для загрузки и отображения новостей при загрузке страницы
    document.addEventListener('DOMContentLoaded', () => {
        const news = loadNews();
        displayNewsCards(news);
    });
</script>
{% endblock %}

apps/news/templates/news/view_news_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ news_item.headline }}</title>
    <link rel="stylesheet" href="{% static 'news/detail-style.css' %}">
</head>
<body>
    <div class="container">
        <h1>{{ news_item.headline }}</h1>
        <div class="news-detail">
            {% if news_item.image %}
                <img src="{{ news_item.image.url }}" alt="{{ news_item.headline }}" class="news-image">
            {% endif %}
            <p>{{ news_item.content }}</p>
            <p><strong>Дата публикации:</strong> {{ news_item.publication_date }}</p>
            <div class="edit-buttons">
{#                <a href="{% url 'edit_news' news_item.id %}" class="update-button">Редактировать</a>#}
{#                <a href="{% url 'delete_news' news_item.id %}" class="delete-button">Удалить</a>#}
            </div>
        </div>
        <a href="{% url 'news_list' %}" class="back-button">Назад на страницу новостей</a>
    </div>
</body>
</html>